'''
Django settings for safe project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
'''

import os
from dotenv import load_dotenv


load_dotenv(verbose=True)


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'bc(u+!t&=%07@1w27zv=iffr*82ffn(+(i@efawefaewfawefjkn53d#o!9^^j26vpn')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', False)
ENV = os.getenv('ENV') or ('dev' if DEBUG else 'prod')
BOOTPAY_REST_KEY = os.getenv('BOOTPAY_REST_KEY')
BOOTPAY_SECRET = os.getenv('BOOTPAY_SECRET')
# bootpay = BootpayBackend(BOOTPAY_REST_KEY, BOOTPAY_SECRET)

REDIS_URL = (
    os.getenv('PROD_REDIS_URL')
    if ENV == 'prod'
    else os.getenv('DEV_REDIS_URL')
    if ENV == 'dev'
    else os.getenv('LOCAL_REDIS_URL', 'redis://127.0.0.1:6379')
)

# Application definition

INSTALLED_APPS = []


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': os.getenv('MYSQL_PROD_DATABASE', 'gold')
#         if ENV == 'prod'
#         else os.getenv('MYSQL_DEV_DATABASE', 'gold')
#         if ENV == 'dev'
#         else 'gold',
#         'USER': os.getenv('MYSQL_USER', 'gold') if ENV != 'local' else 'gold',
#         'PASSWORD': os.getenv('PROD_MYSQL_PASSWORD', 'gold') if ENV != 'local' else 'gold',
#         'HOST': os.getenv('MYSQL_HOST', '127.0.0.1'),
#         'PORT': os.getenv('MYSQL_PORT', 3306),
#         'CONN_MAX_AGE': 600,
#         'OPTIONS': {
#             'charset': 'utf8mb4',
#         },
#     },
# }


# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": REDIS_URL,
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         },
#         "TIMEOUT": 5,
#     }
# }


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True
